CREATE TABLE tweets_extraction
(song varchar ,
artist varchar,
music_platform varchar,
text varchar,
createdat varchar,
geolocation varchar,
source varchar,
hashtags varchar,
name varchar,
id varchar,
screen_name varchar,
description varchar,
followers_count integer,
friends_count integer,
listed_count integer,
favourites_count integer,
statuses_count integer,
language varchar,
mention varchar,
location varchar,
text_original varchar);
